---
- hosts: crunch
  connection: local
  
  vars_prompt:

    - name: target_host
      prompt: Please enter the target IP address
      private: no
      
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts  
        
- name: CONFIGURE ROUTER
  hosts: router
  gather_facts: false
  connection: network_cli

    - name: CONFIGURE DOMAIN
      ios_config:
        save_when: modified
        lines:
          - ip domain name usbank.com

    - name: EIGRP
      ios_config:
        save_when: modified
        lines:
          - network 192.168.99.0 0.0.0.255
        parents: router eigrp 69
