--- 
- name: Running Show Commands
  hosts: routers
  gather_facts: false 
  connection: network_cli 
 
  tasks: 
   - name: Run Many Commands  
     ios_command: 
       commands: 
       - show version
       
     register: output

...    