--- 
- name: Running Show Commands
  hosts: routers
  gather_facts: false 
  connection: network_cli 
 
  tasks: 
   - name: Run Many Commands  
     ios_command: 
       commands: 
       - show ip interface brief

     register: my_config

   - name: Saving Output
     copy:
         content: "{{ my_config.stdout[0] }}"
         dest: /home/devasc/Desktop/US-Bank/US_Bank_Capstone_Project_files/IP-Interface/"{{inventory_hostname}}-IP's.txt"
...        