--- 
- name: Running Show Commands
  hosts: R1
  gather_facts: false 
  connection: network_cli 

  tasks: 
   - name: Add Loopback 0-6
     ios_config: 
       save_when: modified 
       lines: 
         - '{{ item.lines }}'
       parents: '{{ item.parents }}'
     loop:
        - { parents: "interface loopback0", lines: "ip address 10.100.10.10 255.255.255.0" }
        - { parents: "interface loopback1", lines: "ip address 10.101.1.1 255.255.255.0" }
        - { parents: "interface loopback2", lines: "ip address 10.102.1.2 255.255.255.0" }
        - { parents: "interface loopback3", lines: "ip address 10.103.1.3 255.255.255.0" }
        - { parents: "interface loopback4", lines: "ip address 10.104.1.4 255.255.255.0" }
        - { parents: "interface loopback5", lines: "ip address 10.105.1.5 255.255.255.0" }
        - { parents: "interface loopback6", lines: "ip address 10.106.1.6 255.255.255.0" }




     register: output
   

