--- 
- name: Running Show Commands
  hosts: routers
  gather_facts: false 
  connection: network_cli 
 
  tasks: 
   - name: Configure OSPF  
     ios_config: 
       save_when: modified 
       lines: 
         - network 0.0.0.0 0.0.0.0 area 0
         - distance 120
         - default-information originate
       parents: router ospf 1

     register: output
   

