---
- hosts: localhost
  gather_facts: no
  
  vars_prompt:

    - name: firstFile
      prompt: What is the first file?
      private: no

    - name: secondFile
      prompt: What is the second file?
      private: no  

  tasks:
    - name: "Compare and show difference"
      copy:
        src: ./show-run/{{ firstFile }}.txt
        #src: ./show-run/192.168.122.10.txt
        dest: ./show-run/{{ secondFile }}.txt
        #dest: ./show-run/baseline.txt
      check_mode: yes
      diff: yes
