---
- hosts: crunch
  connection: local

  vars_prompt:
  - name: target_host
    prompt: Please enter the target IP address
    private: no
  
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts


- name: CAPTURE SHOWRUN 
  hosts: dynamically_created_hosts
  connection: network_cli
  gather_facts: False

  tasks:
  - name: Show Run
    ios_command:
      commands:
        - show run #show run command on the device
    register: config

  - name: save output to local directory
    copy:
      content: "{{ config.stdout | replace('\\n', '\n') }}"           
      dest: "show-run/{{ inventory_hostname }}.txt"
